version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: '-'
